# Generated by Django 5.1.7 on 2025-12-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи клиентов'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(to='core.service', verbose_name='Выбранные услуги'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], default='new', max_length=20, verbose_name='Статус записи'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание / о себе'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фотография мастера'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('haircut', 'Стрижки'), ('beard', 'Бритьё и оформление бороды'), ('care', 'Уход'), ('complex', 'Комплексные процедуры')], default='haircut', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Длительность (в минутах)'),
        ),
    ]
