# Generated by Django 5.1.7 on 2026-01-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма предоплаты'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prepayment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Способ предоплаты'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prepayment_paid',
            field=models.BooleanField(default=False, verbose_name='Предоплата оплачена'),
        ),
    ]
