# Generated by Django 5.1.7 on 2026-01-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_prepayment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='10:00', verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(default='22:00', verbose_name='Конец рабочего дня')),
            ],
            options={
                'verbose_name': 'Рабочие часы',
                'verbose_name_plural': 'Рабочие часы',
            },
        ),
    ]
