# Generated by Django 5.1.7 on 2026-01-16 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='С')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='До')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='core.master', verbose_name='Мастер (если пусто — блокировка для всех)')),
            ],
            options={
                'verbose_name': 'Блокировка времени',
                'verbose_name_plural': 'Блокировки времени',
                'ordering': ['-date', 'time_from'],
            },
        ),
    ]
